server:
  port: 8888

spring:
  application:
    name: config-server
  
  cloud:
    config:
      server:
        git:
          uri: file:///${CONFIG_REPO_PATH}
          default-label: main
          clone-on-start: true

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
# Logging
logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG